import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

dimensions = { columns = 120, lines = 25 }

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 22

[colors]
draw_bold_text_with_bright_colors = true
